# Generated by Django 4.2 on 2026-02-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(max_length=200)),
                ('message_title', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('tip', 'Health Tip'), ('warning', 'Warning'), ('info', 'Information'), ('reminder', 'Reminder')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'awareness_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(upload_to='prescriptions/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('patient_name_extracted', models.CharField(blank=True, max_length=200, null=True)),
                ('age_extracted', models.IntegerField(blank=True, null=True)),
                ('disease_extracted', models.CharField(blank=True, max_length=200, null=True)),
                ('treatment_duration_days', models.IntegerField(default=0)),
                ('total_medicines', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('ocr_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patient')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('timing', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.IntegerField(default=0)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('total_doses_per_day', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'medicines',
                'ordering': ['medicine_name'],
            },
        ),
    ]
