# Generated by Django 4.2 on 2026-03-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_medicine_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription'),
        ),
    ]
